spring:
  thymeleaf.cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shortener
    username: root
    password: root1234!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true