services:
  mysql:
    image: mysql:8.0
    container_name: shortener
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234!
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/